### PR TITLE
fixes #232: Clicking toolbar TodoItem lifts TodoItem

### LINKED ISSUE #232: Bug: Clicking toolbar TodoItem should liftListItem
## Current behaviour: 
Clicking toolbar TodoItem do not remove list item

## Expected behaviour:
Like hitting Shift+Tab inside TodoItem

### PR DESCRIPTION
**Pull request by Chrissi2812**

### CODE REVIEW

**Comment by philippkuehn** [comment]
This would be too easy. This throws an error whenever you select a checked **and** unchecked todo item and run this command 😩

```
TransformError: Inconsistent open depths
    at new l (https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/vendor.3966885edcef34e080ad.js:1:128946)
    at e.p.step (https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/vendor.3966885edcef34e080ad.js:1:131041)
    at https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/vendor.3966885edcef34e080ad.js:1:76843
    at https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/vendor.3966885edcef34e080ad.js:1:77090
    at https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/vendor.3966885edcef34e080ad.js:1:255556
    at Array.isArray.a.<computed> (https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/vendor.3966885edcef34e080ad.js:1:300438)
    at ze (https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/app.72d0eba7fa6539028703.js:7:11236)
    at HTMLButtonElement.t (https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/app.72d0eba7fa6539028703.js:7:12977)
    at HTMLButtonElement.r._wrapper (https://deploy-preview-278--scrumpy-tiptap.netlify.com/assets/js/app.72d0eba7fa6539028703.js:7:48304)
```

**Comment by philippkuehn** [comment]
Hmm, when defining `content: 'paragraph block*'`  you can paste any block items into list items. For regular lists this is fine but for todo lists I would like to prevent this behavior. ProseMirror lists are killing me 🙃
May-07-2019 14-41-30

**Comment by Chrissi2812** [comment]
@philippkuehn We could however allow `todo_lists` within `todo_items`
nested-todos-2

**Comment by philippkuehn** [comment]
Yeah I already thought about that feature but I would expect nested todo item to also be checked/unchecked. But maybe this is something that everyone would handle different so it would be nice to have an option for it. And then I never thought about it again :D

**Comment by philippkuehn** [comment]
Why do you get rid of `splitToDefaultListItem`? Because now a checked item will be created after a checked item.
May-08-2019 12-32-37

**Comment by Chrissi2812** [comment]
I've played around a bit with that toggle for nested todo items.

https://codesandbox.io/s/64lmxj5x5k

But that is rather hacky and doesn't work always, but maybe it's a starting point for someone else.
nested-todos

**Comment by Chrissi2812** [comment]
> Why do you get rid of `splitToDefaultListItem`? Because now a checked item will be created after a checked item.
> May-08-2019 12-32-37

If you are in a nested todo_list and press enter to make a new todo_item it throws this error and jumps to the next todo_item instead.

nested-todos-error

```
 Uncaught ReferenceError: Fragment is not defined
    at _splitListItem (splitToDefaultListItem.js:57)
    at Plugin.eval (keymap.js:91)
    at eval (index.js:3087)
    at EditorView.someProp (index.js:4455)
    at editHandlers.keydown (index.js:3087)
    at HTMLDivElement.view.dom.addEventListener.view.eventHandlers.<computed> (index.js:3033)
```

Which is caused by this line of code, and I didn't know where Fragment would get definded?

https://github.com/scrumpy/tiptap/blob/42740690e782e5cc0c830c1ddcbbd50df3f1003f/packages/tiptap-commands/src/commands/splitToDefaultListItem.js#L49

**Comment by Chrissi2812** [comment]
@philippkuehn Nevermind the last comment.

This was missing from the `splitToDefaultListItem`
```js
import { Fragment, Slice } from 'prosemirror-model'
```

Now it works 🎉

**Pull request merged**
