### PR TITLE
Allow Extensions to redefine the behaviour of setSelection

### PR DESCRIPTION
**Pull request by rmckayfleming**
I've been implementing CodeMirror within ProseMirror per the [ProseMirror example](https://prosemirror.net/examples/codemirror/). However, the example redefines the behaviour of setSelection on the NodeView so that it focuses the CodeMirror instance. This PR allows Extensions to define a new setSelection function.

### CODE REVIEW

**Comment by philippkuehn** [comment]
thank you!

**Comment by BrianHung** [comment]
@rmckayfleming I'm looking through that ProseMirror implementation of a CodeMirror block. How did you manage to call focus on `this.cm` from `setSelection`? Did you choose to initialize it within `get view()` or within the Node constructor? Thanks.

**Comment by rmckayfleming** [comment]
@BrianHung this.cm is initialized from within the custom vue component.

**Comment by BrianHung** [comment]
To access the CodeMirror instance in the custom Vue component from setSelection, did you end up using `this.vm.cm` then?

**Pull request merged**
