### PR TITLE
Register mention based on matcher char

### PR DESCRIPTION
**Pull request by AveryBibeau**
There needs to be a unique identifier for registered mentions when using multiple instances with different matcher characters. Otherwise the `mention` node in the schema is overwritten by the last registered `Mention` instance

### CODE REVIEW

**Comment by AveryBibeau** [comment]
While updating the examples with a second Mention instance I realized `get name` is used in naming commands and other fields so `commands.mention` would have to be `commands['mention-@']`
Any ideas for naming that would uniquely identify Mention instances while not disrupting syntax? I'm also worried changing `get name` could break existing code for others

**Comment by AveryBibeau** [comment]
Added a `tag` option to `Mention` for identifying separate instances. Defaults to just using `mention` as the instance name so existing code like `commands.mention( ... )` still works. Adding `tag: 'hashtag'` to the Mention options will name the instance `mention_hashtag`. Also adds `data-mention-tag` to the DOM element for identifying what kind of mention it is.

**Comment by philippkuehn** [comment]
Hey @AveryBibeau. Sorry for the late response. I'm not sure about the naming. You've added a `tag` option. Maybe `type` is a better name for it? So type could basically `user` or `hashtag` or whatever.

**Comment by AveryBibeau** [comment]
@philippkuehn That's a fair point, I've changed the option name from `tag` to `type` now

**Comment by AlecTroemel** [comment]
First of all thanks for this awesome project! Is there any update on this PR? Would love to see this merged!

**Comment by philippkuehn** [comment]
Hey, sorry for my late response but I'm still thinking about this one. What I do not like is that we do some work here that is only usable for this one extension.

```js
export default class Mention extends Node {

  get name() {
    return this.options.type === 'default' ? 'mention' : `mention_${this.options.type}`
  }

}
```

So I was thinking of a method available for all extensions. Something like that:

```js
new Mention({ options }).setName('hashtag')
```

But that means, that we can't use a simple getter function for `name()` because the name attribute can be overwritten after initialization. Maybe we could implement a `init()` method instead? This would be a breaking change.

```diff
export default class Mention extends Node {

-  get name() {
-    return 'hashtag'
-  }

+  init() {
+    this.setName('hashtag')
+  }

}
```

What do you think? Any suggestions for better method names?

**Comment by philippkuehn** [comment]
I don't want to change the current behavior. You can always extend extensions if you want to overwrite names.

```js
import {Mention} from 'tiptap-extensions'

export default class Hashtag extends Mention {
  get name() {
    return 'hashtag'
  }
}
```

**Comment by iamcodemaker** [comment]
To make this work I had to at minimum set the following properties using both the `extend()` and `configure()` methods. Obviously you'll need other properties to have a fully working editor instance, but these were the minimum set need to get the desired behavior. I did this along side another mention instance using the defaults (`@` as the char) with no issues. This also worked with the `generateJSON()` method to generate json from html to hydrate the editor state. I'm working in typescript.

```typescript
import { Editor } from '@tiptap/core'
import Mention from '@tiptap/extension-mention'
import { PluginKey } from 'prosemirror-state'

const editor = new Editor({
  extensions: [
    Mention
      .extend({
        name: 'hashtag',
        suggestion: {
          char: '#',
        },
      })
      .configure({
        suggestion: {
          char: '#',
          pluginKey: new PluginKey('hashtag'),
        },
      }),
  ],
})
```

**Pull request closed without merging**
