### PR TITLE
optimize image

### PR DESCRIPTION
**Pull request by jjangga0214**
The image file size has been reduced by 69%.

* file: /examples/assets/static/images/open-graph.png
* before: 53.58 kb
* after: 16.41 kb

### CODE REVIEW

**Comment by philippkuehn** [comment]
All images will be optimized in the build process (`imagemin-webpack-plugin`). So in production this open graph image is already about 16kb.

**Comment by jjangga0214** [comment]
@philippkuehn  This commit is not for production, but for development environment. 

There is 1 commit `56bb2f` by you for the file. So, the image snapshot is recorded in **.git** directory, and it consumes 53.58 kb + alpha (very little extra info, which can be ignored). Developers have it in their working directory ( project root folder except .git ) as well. In total, 53.58 kb + 53.58 kb = **107.16 kb** is used for the image. 

After this commit(PR), 16.41 kb will be recorded in **.git** directory (+ 16.41kb + alpha) and developers will have also 16.41 kb image in their working directory ( - 53.58 kb + 16.41 kb). In total, 107.16 kb + 16.41 kb - 53.58 kb + 16.41 kb = **86.4 kb** would be consumed for the image.

So it's good to optimize the image. 

If you want version control original design source with the best image quality (low compression) though git, I recommend [**git-lfs**](https://git-lfs.github.com/). But I found there's only one commit for the file, so thought it is unlikely to be modified.

**Comment by philippkuehn** [comment]
you made my day 😂

**Comment by jjangga0214** [comment]
@philippkuehn 
Laughing increases endorphin release, so this PR has done a good thing already. 
But I would be glad if you let me know the concrete reason not merging this.
 
That shouldn't just because @hanspagel thumbed down :) (I'm kidding)

**Pull request closed without merging**
