### PR TITLE
toggle between unordered_list and ordered_list

### LINKED ISSUE #4: toggle between bullet list and ordered list not working
Find a way to toggle bullet lists and ordered lists (and maybe todolists)
aug -27-2018 15-27-29

### PR DESCRIPTION
**Pull request by Chrissi2812**
I'm not 100% sure that this is the way to go 🙈

fixes #4

### CODE REVIEW

**Comment by philippkuehn** [comment]
Tough challenge! :D Sometimes there is an issue when using with nested lists :(

May-17-2019 16-08-19

**Comment by Chrissi2812** [comment]
Always good that you find these "edge cases" 
- If empty selection the current list type will change instead of current list_item beeing wrapped by other list type. For nested lists TAB or Command must be used.
- Unwrapping is now fixed (Hopefully in any case, this time).

togglelist

**Comment by Chrissi2812** [comment]
Also if selection contains nested lists only the top level list type will change.

**Comment by philippkuehn** [comment]
Thank you sooo much! But there is another edge case 😅

You can't do anything if there is a list within a blockquote 👀

May-20-2019 13-30-12

**Comment by Chrissi2812** [comment]
Okay have to do more work on this. Currently Todo Lists are broken....

**Comment by Chrissi2812** [comment]
Now you can even have lists within blockqoutes within lists within blockqoutes (Inception 😅)

image

**Comment by philippkuehn** [comment]
Awesome! Looks good so far – can't find any other edge case 😅

**Pull request merged**
