### PR TITLE
fix(placeholder) appeared when not empty (#463)

### LINKED ISSUE #463: Placeholder appeared when content is not empty
**Describe the bug**
In my project, placeholder is only visible when the editor is completely empty, but i'm just empty in the first line, and have content the next line, now i focus the first line, placeholder appeared. 

**Steps to Reproduce / Codesandbox Example**
1. Empty first line.
2. Input some content in the second line.
3. Focus the first line.
4. Placeholder appeared.

Can reproduce in https://tiptap.scrumpy.io/placeholder

**Expected behavior**
Only show placeholder when the editor is completely empty.

**Screenshots**
屏幕快照 2019-09-26 14 47 57

**Environment**
 - OS Mac
 - Browser Chrome
 - Desktop

### PR DESCRIPTION
**Pull request by TimvdEijnden**
fixes #463

### CODE REVIEW

**Comment by Leecason** [comment]
Is this pr ready to merge?

**Comment by TimvdEijnden** [comment]
@Leecason I see one check is failing. I'll fix it. Then it should be ready

**Comment by TimvdEijnden** [comment]
And it's ready!

**Comment by TimvdEijnden** [comment]
@philippkuehn Could you have a look please?

**Comment by iliyaZelenko** [comment]
@philippkuehn there are only two lines of changes, I think you can easily check it.

**Comment by philippkuehn** [comment]
i've added a fix for #463 in https://github.com/scrumpy/tiptap/commit/1472254913c984fadba33c08db2366d4f65de711

there is a new `emptyEditorClass` option you can use for `Placeholder`

**Pull request closed without merging**
